name: jonisnowhere
favicon: null
layout_spectrum: 0.002180904382839799
typography_spectrum: 0.8503450681455433
title: 'part-time flaneur '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2962518138810992
  lightness: 0.6021965448744595
  saturation: 0.8659401691984385
  rhythmicContrast: 0.4215357485227287
purpose: []
