name: jonisnowhere
favicon: null
layout_spectrum: 0.70017
typography_spectrum: 0.32941
title: republic of neurons
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#0f0f0f'
    - '#75889e'
    - '#555555'
    - '#ca6c33'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
