name: jonisnowhere
favicon: null
layout_spectrum: 0.71949
typography_spectrum: 0.32941
title: republic of neurons
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#02070e'
    - '#c3d2e7'
    - '#736f77'
    - '#2d3237'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
