name: jonisnowhere
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8503450681455433
title: neo-apothecary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#262b39'
    - '#080a0d'
    - '#49536f'
    - '#b1c7e8'
  brandStrength: 0.125
  lightness: 0.6021965448744595
  saturation: 0.375
  rhythmicContrast: 0.4215357485227287
purpose: []
