name: part-time flaneur
favicon: null
layout_spectrum: 0.9598
typography_spectrum: 0.46509
title: jonisnowhere
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#262b39'
    - '#080a0d'
    - '#49536f'
    - '#b1c7e8'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
